"""Add cascade delete to book relations

Revision ID: 64345ac0ab86
Revises: 
Create Date: 2025-05-26 11:02:36.740139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64345ac0ab86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 1. Создай новую временную таблицу с нужными ondelete='CASCADE'
    op.create_table(
        'book_genre_new',
        sa.Column('book_id', sa.Integer(), sa.ForeignKey('book.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('genre_id', sa.Integer(), sa.ForeignKey('genre.id', ondelete='CASCADE'), primary_key=True)
    )
    # 2. Перенеси данные
    op.execute('INSERT INTO book_genre_new (book_id, genre_id) SELECT book_id, genre_id FROM book_genre')
    # 3. Удали старую таблицу
    op.drop_table('book_genre')
    # 4. Переименуй новую таблицу
    op.rename_table('book_genre_new', 'book_genre')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'genre', ['genre_id'], ['id'])

    # ### end Alembic commands ###
