"""Добавлена таблица просмотров книг

Revision ID: ac9aed15a4ba
Revises: 80ba8c97500e
Create Date: 2025-05-27 00:23:02.654085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9aed15a4ba'
down_revision = '80ba8c97500e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('cover', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('review', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('review', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])
    #     # batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('cover', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    op.drop_table('book_view')
    # ### end Alembic commands ###
